// ncl_gate netlist files - generated from Cadence Virtuoso Comporser schematic 
// generated by Matthew Kim - 24/05/2014

./netlist/cds_globals.v
./netlist/nfet_b.v
./netlist/pfet_b.v
./netlist/inv.v
./netlist/inv4x.v
./netlist/th12.v
./netlist/th12b.v
./netlist/th13.v
./netlist/th14.v
./netlist/th22.v
./netlist/th22r.v
./netlist/th22s.v
./netlist/th23.v
./netlist/th23w2.v
./netlist/th24.v
./netlist/th24comp.v
./netlist/th24w2.v
./netlist/th24w22.v
./netlist/th33.v
./netlist/th33r.v
./netlist/th34.v
./netlist/th34w2.v
./netlist/th34w3.v
./netlist/th34w22.v
./netlist/th34w32.v
./netlist/th44.v
./netlist/th44w3.v
./netlist/th44w22.v
./netlist/th44w322.v
./netlist/th44w322a.v
./netlist/th54w22.v
./netlist/th54w32.v
./netlist/th54w322.v
./netlist/thand0.v
./netlist/thxor0.v
./netlist/thxor0n.v

./ncl_simlib_ref.v
./stimulus_gen.v
./tb_uncle_gates.v
